# Configuracion especifica de NexusCatalogoMs
server.port=${SERVER_PORT:8082}
server.servlet.context-path=/NexusMS

spring.datasource.url=jdbc:postgresql://localhost:5434/db_catalogo
spring.datasource.username=${DB_CATALOGO_USERNAME:admin_nexus}
spring.datasource.password=${DB_CATALOGO_PASSWORD:admin_password_123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
