# Configuracion especifica de NexusIngresoMs
server.port=${SERVER_PORT:8083}
server.servlet.context-path=/NexusMS

spring.datasource.url=jdbc:postgresql://localhost:5435/db_ingresos
spring.datasource.username=${DB_INGRESOS_USERNAME:admin_nexus}
spring.datasource.password=${DB_INGRESOS_PASSWORD:admin_password_123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.remote.seguridad.base-url=${REMOTE_SEGURIDAD_BASE_URL:http://nexus-seguridad-ms}
app.remote.seguridad.usuario-por-id=${REMOTE_SEGURIDAD_USUARIO_POR_ID:/NexusMS/api/usuarios/{id}}

app.remote.catalogo.base-url=${REMOTE_CATALOGO_BASE_URL:http://nexus-catalogo-ms}
app.remote.catalogo.producto-por-id=${REMOTE_CATALOGO_PRODUCTO_POR_ID:/NexusMS/api/productos/{id}}
app.remote.catalogo.actualizar-stock=${REMOTE_CATALOGO_ACTUALIZAR_STOCK:/NexusMS/api/productos/{id}/stock}

spring.cloud.circuitbreaker.resilience4j.enabled=true
resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.configs.default.sliding-window-size=4
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=2
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.seguridadService.base-config=default
resilience4j.circuitbreaker.instances.seguridadService.ignore-exceptions[0]=net.hwongu.nexus.ingreso.be.exception.BadRequestException
resilience4j.circuitbreaker.instances.catalogoService.base-config=default
resilience4j.circuitbreaker.instances.catalogoService.ignore-exceptions[0]=net.hwongu.nexus.ingreso.be.exception.BadRequestException
