server {
    listen 80;
    server_name localhost;

    location / {
        rewrite ^/$ /NexusFrontEnd/ redirect;
    }

    location /NexusFrontEnd/ {
        alias /usr/share/nginx/html/NexusFrontEnd/;
        try_files $uri $uri/ /NexusFrontEnd/index.html;
    }

    location /mfe-auth/ {
        alias /usr/share/nginx/html/mfe-auth/;
        try_files $uri $uri/ /mfe-auth/index.html;
    }

    location /mfe-dashboard/ {
        alias /usr/share/nginx/html/mfe-dashboard/;
        try_files $uri $uri/ /mfe-dashboard/index.html;
    }

    location /mfe-categories/ {
        alias /usr/share/nginx/html/mfe-categories/;
        try_files $uri $uri/ /mfe-categories/index.html;
    }

    location /mfe-users/ {
        alias /usr/share/nginx/html/mfe-users/;
        try_files $uri $uri/ /mfe-users/index.html;
    }

    location /mfe-products/ {
        alias /usr/share/nginx/html/mfe-products/;
        try_files $uri $uri/ /mfe-products/index.html;
    }

    location /mfe-revenues/ {
        alias /usr/share/nginx/html/mfe-revenues/;
        try_files $uri $uri/ /mfe-revenues/index.html;
    }
}
