# Nombre de la aplicacion
spring.application.name=nexus-config-server

# Puerto del servidor de configuracion
server.port=${SERVER_PORT:9099}

# Activa el perfil native para leer desde el sistema de archivos local
spring.profiles.active=native

# Ubicacion del repositorio local de configuracion.
# Se contemplan distintos working directories habituales del IDE.
spring.cloud.config.server.native.search-locations=file:${user.dir}/config-repo,file:${user.dir}/NexusConfigServerMs/config-repo,file:${user.dir}/../NexusConfigServerMs/config-repo
